### ISSUE TITLE
Support XML based APIs

### ISSUE THREAD

**Issue by olsona** [dtinit/data-transfer-project#106]
Some APIs use XML instead of JSON, such as Shutterfly. 

Shouldn't be that hard to add support: http://www.baeldung.com/jackson-xml-serialization-and-deserialization

**Comment by lisad** [comment]
There's nothing preventing XML APIs from being supported in an extension, so either this is already possible (although with more work than just pointing a serializer at the data model) or not planned (not sure how useful it truly is to just point a serializer at the data model since companies have their own data models in their APIs.

**Comment by lisad** [comment]
After discussion with other maintainers, going to close this as "not planned" in that we're not planning to do work to explicitly add extra support for XML since it's already possible to do .
