### ISSUE TITLE
Add support for mounting/syncing iCloud drive on Linux

### ISSUE THREAD

**Issue by ryuheechul** [dtinit/data-transfer-project#1396]
Currently there is no such support on Linux platform according to https://support.apple.com/en-ca/guide/icloud/mm203b05aec8/icloud

This makes the experience of syncing files between Linux and other Apple devices very poor. Instead of a Dropbox style experience, users have to upload and download files manually through a browser. Apple [opened up to Windows already](https://support.apple.com/en-ca/guide/icloud-windows/icw0144825a5/icloud) and I believed the same can be and should be done for Linux platform as well.

**Comment by calumcalder** [comment]
Hi @ryuheechul - I think this issue may be in the wrong place; the Data Transfer Project is open-source infrastructure to support users porting data between platforms. Your issue seems like a feature request for Apple, which you can send to Apple at https://www.apple.com/feedback/.

I'm going to close this issue for now, as I don't think it's within the scope of DTP.

**Comment by upintheairsheep** [comment]
rClone is what you're looking for. This si something esle.
